Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -10,23 +10,25 @@ jobs:
     steps:
       - name: Checkout Repo
         uses: actions/checkout@v3
-      - name: Setup Python
-        uses: actions/setup-python@v4
-        with:
-          python-version: '3.10'
-      - name: Install Dependencies
-        run: |
-          python -m pip install --upgrade pip
-          pip install pyyaml
       - name: Run Feed Generator
-        run: python feed.py
-      - name: Commit files
-        run: |
-          git config --local user.email "abc@abc.com"
-          git config --local user.name "github"
-          git commit -a -m "Add changes" || echo "Commit error"
-      - name: Push Repo
-        uses: ad-m/github-push-action@master
-        with:
-            github_token: ${{secrets.GITHUB_TOKEN}}
-            branch: ${{ github.ref}}
+        uses: venkatsa/podcast-generator@main
+      # - name: Setup Python
+      #   uses: actions/setup-python@v4
+      #   with:
+      #     python-version: '3.10'
+      # - name: Install Dependencies
+      #   run: |
+      #     python -m pip install --upgrade pip
+      #     pip install pyyaml
+      # - name: Run Feed Generator
+      #   run: python feed.py
+      # - name: Commit files
+      #   run: |
+      #     git config --local user.email "abc@abc.com"
+      #     git config --local user.name "github"
+      #     git commit -a -m "Add changes" || echo "Commit error"
+      # - name: Push Repo
+      #   uses: ad-m/github-push-action@master
+      #   with:
+      #       github_token: ${{secrets.GITHUB_TOKEN}}
+      #       branch: ${{ github.ref}}
